# Generated by Django 3.0.5 on 2020-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AddField(
            model_name='token',
            name='token_string',
            field=models.CharField(default='a', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
