# Generated by Django 3.0.5 on 2020-04-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200409_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Token'),
            preserve_default=False,
        ),
    ]
