# Generated by Django 3.0.5 on 2020-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
